### ISSUE TITLE
initialize Power 5, Group of 5, and FCS to different values

### ISSUE THREAD

**Issue by drewbennison** [kylebennison/staturdays#23]
1500 - P5
1400 - G5
1300 - FCS

-Values up for discussion.

**Comment by kylebennison** [comment]
alternatively, we can test a different in-game elo adjustment (similar to what we do with Home-Field Advantage), e.g. -50 for FCS teams when facing FBS

**Comment by kylebennison** [comment]
issue i'm having with this is that we can initialize at lower scores in 2000, but what do we do if a team has since moved up into Power 5 or down into group of 5 or FCS (e.g. App State)? Wondering if initializing isn't enough and we should make an adjustment each game.

**Comment by kylebennison** [comment]
More notes to try
- Regress each group differently, p5 should regress to 1500, g5 to g5 mean, and d3 to d3 mean. (will have to add conference data to elo tibble)
- Test using their current day conference to initialize a team vs. using their 2000 data

**Comment by kylebennison** [comment]
With all teams regressing to 1500 each season, D3 min out at 1000, G5 at 1500 initial, and Brier of 

0.173222

**Comment by drewbennison** [comment]
Using 2019 conferences gives brier of .173 with g5 =1500, d3=1000

**Comment by drewbennison** [comment]
d3=500, g5=1000 = .172

**Comment by drewbennison** [comment]
FBS Independents now included as P5, regression based on initial conference rating

**Comment by drewbennison** [comment]
we did this good
