### ISSUE TITLE
implement game-control and win/loss margin into Elo

### ISSUE THREAD

**Issue by kylebennison** [kylebennison/staturdays#37]
**Game Control:** For how many plays/seconds of the game did they have WP > 95, or simply have a lead greater than X depending on the quarter.

**Win/Loss Margin:** Win by FG, One-score, two-score, three-score, etc. and _when_ did they win it? Last second FG, or a while earlier? If favored and last second win, uh oh - less or no credit. If underdog and last second loss, improve Elo.

**Comment by drewbennison** [comment]
Game control would be more useful for a betting model.
