### ISSUE TITLE
WIP betting model data source error

### ISSUE THREAD

**Issue by drewbennison** [kylebennison/staturdays#86]
To run betting_model_2022_07_06, betting_data_prep has to be run first.

In betting_data_prep, the following line looks for a plays data set that does not exist:

```
# Get play-by-play
plays <- fread("Data/plays_2014_2020.csv")
```

Should we create this plays data set each time, or is this something we should create once and store in Data/?

@kylebennison

**Comment by drewbennison** [comment]
Closing as not a bug. User to run plays code as data set is too large to store on GitHub.

**Comment by drewbennison** [comment]
@kylebennison  betting_prepped.rds file added to Data/ and pushed.

**Comment by kylebennison** [comment]
thanks @drewbennison!
