### ISSUE TITLE
Twitter: Sentiment analysis of gameday hosts

### ISSUE THREAD

**Issue by kylebennison** [kylebennison/staturdays#89]

**Comment by drewbennison** [comment]
Tasks:
- [ ] Get Twitter scraping code set back up
- [ ] Scrape during College Gameday

**Comment by drewbennison** [comment]
Completed the code for this. Marking as closed for now because I do not think the results are actually that interesting given the nature of Twitter (more likely to be fans of certain hosts due to age, etc.) Can potentially post results as a Tweet, but would like to focus on other updates.
